### ISSUE TITLE
Fit to F7 plugin standards and release

### ISSUE THREAD

**Issue by nolimits4web** [boynet/Framework7-Indexed-List-plugin#7]
Plugin need to be fitted to F7 plugin standards to be posted on website. I will recommend:

* files/folder structure like here: https://github.com/nolimits4web/Framework7-3D-Panels. It will contain `demo` folder to be able to see results right from repo, `src` folder for development and `dist` folder with full and minified release versions
* use your own banner with your credentials and plugin version like in beginning of this file: https://github.com/nolimits4web/Framework7-3D-Panels/blob/master/dist/framework7.3dpanels.js
* release it by adding git tags
* register it at Bower, so it could be easily installed like `bower install framework7-indexed-list`

**Comment by boynet** [comment]
so I make all the reqiuired changes :) except 'release it by adding git tags' what does it mean?

**Comment by nolimits4web** [comment]
If you add git tag, it will allow to register plugin in bower and in npm. Also you will be able to downloaded archives with different versions. Here is a good tutorial about it http://git-scm.com/book/en/v1/Git-Basics-Tagging

You'll only need to commands:
```
git tag -a v1.2 -m 'version 1.2' 9fceb02
git push origin --tags
```

**Comment by boynet** [comment]
thanks I think I got it, I checked it by running 
````
bower info framework7-indexed-list-plugin 
````
and got: 
````
availabe versions: 
- 0.1.0

**Comment by nolimits4web** [comment]
Great, will add it to plugins section on website on a days
